version: '3.9'
services:
  arch-xpra:
    build: .
    ports:
      - 9876:9876
    volumes:
      - ./data/logs:/workspace/logs
    entrypoint: sh
    stdin_open: true # docker run -i
    tty: true        # docker run -t